###### network cfgs
pred_type: 'position' # 'position' or 'pose'
input_size: 11  # action dim
output_size: 9  # fingertip poses dim: 9 for position, 21 for pose
hidden_sizes: [128, 256, 256, 256]
normalization: False
#####################

###### run cfgs
exp_name: 'robotiq_forward_model'
log_path: 'logs/models'
#####################

###### train cfgs
train_path: 'data/hand_data/Robotiq3Finger/Robotiq_random_train_Jul_23_21:24:03_2024'    # train dataset path
val_path: 'data/hand_data/Robotiq3Finger/Robotiq_random_val_Jul_23_21:28:16_2024'        # validation dataset path
batch_size: 64
num_workers: 4
epochs: 300
save_interval: 15
do_validation: True

optimizer: 'Adam' # 'SGD' or 'Adam'
lr: 1e-4
beta1: 0.9

scheduler: 'Adaptive' # 'Linear' or 'Adaptive'
# Linear
step_size: 10
gamma: 0.8
# Adaptive
mode: 'min'
factor: 0.8
threshold: 1e-8
patience: 3
verbose:  True
#####################

device: 'cuda:0'

