###### network cfgs
pred_type: 'inverse' # 'position' or 'pose'
input_size: 15   # fingertip poses dim: 15 for position, 35 for pose
output_size: 39 # action dim
hidden_sizes: [256, 256, 256, 256]
normalization: True
#####################

###### run cfgs
exp_name: 'myohand_inverse_model'
log_path: 'logs/models'
#####################

###### train cfgs
train_path: 'data/hand_data/MyoHand/myohand_random_pos_Jun_19_18:24:52_2024'    # train dataset path
val_path: 'data/hand_data/MyoHand/myohand_random_pos_Jun_20_10:29:57_2024'        # validation dataset path
batch_size: 64
num_workers: 4
epochs: 100
save_interval: 5
do_validation: True

optimizer: 'Adam' # 'SGD' or 'Adam'
lr: 1e-4
beta1: 0.9

scheduler: 'Adaptive' # 'Linear' or 'Adaptive'
# Linear
step_size: 10
gamma: 0.8
# Adaptive
mode: 'min'
factor: 0.8
threshold: 1e-6
patience: 3
verbose:  True
#####################

device: 'cuda:0'

