###### network cfgs
use_handmodel: False
input_size: 60  # action dim + hand state dim + object state im (39+15+6)
output_size: 21  # states dim: 15 + 6
hidden_sizes: [512, 512]
#####################

###### run cfgs
exp_name: 'reorientation'
log_path: 'inhand_logs/'
#####################

###### train cfgs
batch_size: 64
num_workers: 4
epochs: 50
do_validation: True

optimizer: 'Adam' # 'SGD' or 'Adam'
lr: 1e-4
beta1: 0.9
weight_decay: 0.01

# scheduler: 'Adaptive' # 'Linear' or 'Adaptive'
# # Linear
# step_size: 10
# gamma: 0.8
# # Adaptive
# mode: 'min'
# factor: 0.8
# threshold: 1e-8
# patience: 3
# verbose:  True
#####################

device: 'cuda:0'

